# Generated by Django 5.2.8 on 2025-11-10 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerlikes',
            options={'verbose_name': 'Лайк к ответу', 'verbose_name_plural': 'Лайки к ответам'},
        ),
        migrations.AlterModelOptions(
            name='questionlikes',
            options={'verbose_name': 'Лайк к вопросу', 'verbose_name_plural': 'Лайки к вопросам'},
        ),
        migrations.AlterModelOptions(
            name='questiontags',
            options={'verbose_name': 'Тег к вопросу', 'verbose_name_plural': 'Теги к вопросам'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=255, verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор вопроса'),
        ),
        migrations.AlterUniqueTogether(
            name='answerlikes',
            unique_together={('user', 'answer')},
        ),
        migrations.AlterUniqueTogether(
            name='questionlikes',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='questiontags',
            unique_together={('question', 'tag')},
        ),
    ]
