# Generated by Django 5.2.8 on 2025-11-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answerlikes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='true - отобразится пользователям', verbose_name='Активно?'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, help_text='true - отобразится пользователям', verbose_name='Активно?'),
        ),
    ]
