# Generated by Django 5.2.8 on 2025-11-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answer_is_active_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_cnt',
            field=models.IntegerField(default=0, verbose_name='Количество ответов'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='questions.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.DeleteModel(
            name='QuestionTags',
        ),
    ]
