# Generated by Django 5.2.8 on 2025-11-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_answers_cnt_question_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, to='questions.tag', verbose_name='Теги'),
        ),
    ]
