# Generated by Django 5.2.8 on 2025-11-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='true - правильный', verbose_name='Правильный ответ?'),
        ),
    ]
