# Generated by Django 5.2.8 on 2025-12-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_questionlikes_type_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
