# Generated by Django 5.2.8 on 2025-12-23 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlikes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answerlikes',
            name='type',
            field=models.BooleanField(default=True, help_text='true - лайк, false - дизлайк', verbose_name='Лайк?'),
        ),
        migrations.AddField(
            model_name='questionlikes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='questionlikes',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_likes', to='questions.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='questionlikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
