# Generated by Django 5.2.8 on 2026-01-22 22:11

from django.db import migrations


from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_answerlikes_is_active_answerlikes_type_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]

