# Generated by Django 5.2.8 on 2026-01-23 14:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20260122_2211'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerLikes',
            new_name='AnswerLike',
        ),
        migrations.RenameModel(
            old_name='QuestionLikes',
            new_name='QuestionLike',
        ),
    ]
