# Generated by Django 5.2.8 on 2025-12-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(max_length=255, upload_to='avatars/', verbose_name='Аватарка пользователя'),
        ),
    ]
