# Generated by Django 5.2.8 on 2025-12-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='original_avatar',
            field=models.ImageField(default=None, max_length=255, upload_to='originalavatars/', verbose_name='Аватарка пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(max_length=255, upload_to='avatars/', verbose_name='Аватарка пользователя (сжатая)'),
        ),
    ]
