# Generated by Django 5.2.8 on 2025-12-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_original_avatar_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='original_avatar',
            field=models.ImageField(max_length=255, upload_to='originalavatars/', verbose_name='Аватарка пользователя'),
        ),
    ]
