# Generated by Django 5.2.8 on 2025-12-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_profile_original_avatar_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
    
